### ISSUE TITLE
when evaluation, why remove entities that not seen?

### ISSUE THREAD

**Issue by koukoulala** [deepakn97/relationPrediction#12]
![image](https://user-images.githubusercontent.com/30341159/69712798-63e7c680-113e-11ea-96ec-8215f559333b.png)
In your code, I find that when you evaluate the test set, the entities that not appeared in train set would be removed.
Can you please explain this operation?
And when I reproduce ConvKB by your code, I can get H@10=0.593 in FB15k-237. Why you report  0.471 ?

**Comment by koukoulala** [comment]
It's just I think if you remove those entities, it would be unfair for other baselines.

**Comment by chauhanjatin10** [comment]
Hi @koukoulala 
We removed the entities which are not a part of the graph since they are not learnt via the graph attention network operations. Any such entities won't be learnt via any method as well. We ran all the other baselines in similar settings, which makes the evaluation fair.
The Hits@10 = 0.593, are from our method which initialises our ConvKB decoder with the embeddings learnt from GAT. Simple ConvKB gives around 0.48 . I hope this clarifies your doubts.
