### ISSUE TITLE
about 2hop neighbors

### ISSUE THREAD

**Issue by namenotexist** [deepakn97/relationPrediction#20]
Did you use all 2-hop neighbors or partial 2-hop neighbors

**Comment by chauhanjatin10** [comment]
Hi @namenotexist . For Freebase, we have used partial 2hops neighbours since the count is extremely large due to the density of the graph. For Wordnet, we used almost all the 2hops neighbours. This remains as the implementation choice since its heavily based on the amount of cuda memory one has. I hope this clarifies your question.
